name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cargo-build-${{ hashFiles('**/Cargo.toml') }}
    - name: Install Linux dependencies
      uses: ./.github/actions/install-linux-deps
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
